---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deployment-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
  - port: {{ .Values.deployment.svc.port }}
    targetPort: {{ .Values.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deployment.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.rollingUpdate.maxUnavailable }}
    type: {{ .Values.deployment.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
      {{- with .Values.deployment.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - image: {{ .Values.image.repository }}:latest
        name: {{ .Values.image.name }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-db-config
        - secretRef: 
            name: {{ .Release.Name }}-db-secret
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        resources:
          requests:
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}
          limits:
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}